In [1]:
!pip install -f http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html h2o

Looking in links: http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html
WARNING: The repository located at h2o-release.s3.amazonaws.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host h2o-release.s3.amazonaws.com'.
Collecting h2o
  Downloading h2o-3.46.0.7-py2.py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from h2o) (2.32.4)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from h2o) (0.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (2025.8.3)
Downloading h2o-3.46.0.7-py2.py3-none-any.whl (265.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.9/265.9 MB 5.1 MB/s eta 0:00:00
Installing collected packages: h2o
Successfully installed h2o-3.46.0.7

In [3]:
# Load common libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
import numpy as np

# Framework libraries
import h2o
from h2o.automl import H2OAutoML
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321. connected.
Warning: Your H2O cluster version is (6 months and 8 days) old.  There may be a newer version available.
Please download and install the latest version from: https://h2o-release.s3.amazonaws.com/h2o/latest_stable.html

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         20 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.7
H2O_cluster_version_age:    6 months and 8 days
H2O_cluster_name:           H2O_from_python_unknownUser_47jlz6
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.168 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.12.11 final
--------------------------  -----------------------------------------------------------------------------------------

In [12]:
# Reading dataset
data = pd.read_csv("train.csv")
data["CabinNoCabin"] = np.where(data["Cabin"].isnull(), "No Cabin", "Cabin")
data["survived"] = np.where(data["Survived"] == 1, "yes", "no")
# data["Age"] = data["Age"].fillna(data["Age"].mean())
data.drop(["PassengerId", "Name", "Ticket", "Cabin", "Survived"], axis = 1, inplace = True)
data.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked CabinNoCabin survived
0       3    male  22.0      1      0   7.2500        S     No Cabin       no
1       1  female  38.0      1      0  71.2833        C        Cabin      yes
2       3  female  26.0      0      0   7.9250        S     No Cabin      yes
3       1  female  35.0      1      0  53.1000        S        Cabin      yes
4       3    male  35.0      0      0   8.0500        S     No Cabin       no

In [13]:
# Split data
train_data, test_data = train_test_split(data, test_size = 0.2)

In [14]:
# Create datasets in the right form for H2O
train_data = h2o.H2OFrame(train_data)
test_data = h2o.H2OFrame(test_data)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [15]:
# Role definition
X = train_data.columns
y = 'survived'
X.remove(y)

In [16]:
# Set up framework
automl = H2OAutoML(max_runtime_secs=300, seed = 1)

In [17]:
# Fit model
automl.train(x = X, y=y, training_frame=train_data)

AutoML progress: |███████████████████████████████████████████████████████████████| (done) 100%

Model Details
=============
H2OStackedEnsembleEstimator : Stacked Ensemble
Model Key: StackedEnsemble_AllModels_5_AutoML_2_20251006_24550


Model Summary for Stacked Ensemble:
key                                        value
-----------------------------------------  ----------------
Stacking strategy                          cross_validation
Number of base models (used / total)       51/51
# GBM base models (used / total)           22/22
# XGBoost base models (used / total)       17/17
# DeepLearning base models (used / total)  9/9
# DRF base models (used / total)           2/2
# GLM base models (used / total)           1/1
Metalearner algorithm                      GBM
Metalearner fold assignment scheme         Random
Metalearner nfolds                         5
Metalearner fold_column
Custom metalearner hyperparameters         None

ModelMetricsBinomial: stackedensemble
** Reported on train data. **

MSE: 0.09090845232882111
RMSE: 0.3015102856103272
LogLoss: 0.31432360504066814
Mean Per-Class Error: 0.11203879612038796
AUC: 0.9210995567109956
AUCPR: 0.9210650079351107
Gini: 0.8421991134219913

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.37033104806734146
       no    yes    Error    Rate
-----  ----  -----  -------  ------------
no     399   39     0.089    (39.0/438.0)
yes    37    237    0.135    (37.0/274.0)
Total  436   276    0.1067   (76.0/712.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.370331     0.861818  156
max f2                       0.240679     0.866619  184
max f0point5                 0.841168     0.886139  77
max accuracy                 0.438375     0.894663  147
max precision                0.944013     1         0
max recall                   0.0560809    1         396
max specificity              0.944013     1         0
max absolute_mcc             0.438375     0.776622  147
max min_per_class_accuracy   0.294054     0.875912  171
max mean_per_class_accuracy  0.370331     0.887961  156
max tns                      0.944013     438       0
max fns                      0.944013     273       0
max fps                      0.0478908    438       399
max tps                      0.0560809    274       396
max tnr                      0.944013     1         0
max fnr                      0.944013     0.99635   0
max fpr                      0.0478908    1         399
max tpr                      0.0560809    1         396

Gains/Lift Table: Avg response rate: 38.48 %, avg score: 39.72 %
group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score      cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  --------  -----------------  ---------------  ---------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.11236                     0.939851           2.59854   2.59854            1                0.940016   1                           0.940016            0.291971        0.291971                   159.854   159.854            0.291971
2        0.150281                    0.923634           2.59854   2.59854            1                0.933065   1                           0.938262            0.0985401       0.390511                   159.854   159.854            0.390511
3        0.200843                    0.89888            2.59854   2.59854            1                0.909343   1                           0.930982            0.131387        0.521898                   159.854   159.854            0.521898
4        0.300562                    0.743951           1.93976   2.37997            0.746479         0.830272   0.915888                    0.897568            0.193431        0.715328                   93.9755   137.997            0.674233
5        0.400281                    0.32432            1.57376   2.17913            0.605634         0.538723   0.838596                    0.808172            0.156934        0.872263                   57.3764   117.913            0.76724
6        0.501404                    0.17306            0.324818  1.80515            0.125            0.221091   0.694678                    0.689769            0.0328467       0.905109                   -67.5182  80.5148            0.656251
7        0.599719                    0.131035           0.18561   1.53965            0.0714286        0.146261   0.592506                    0.600669            0.0182482       0.923358                   -81.439   53.965             0.526097
8        0.699438                    0.109153           0.146397  1.34101            0.056338         0.119696   0.516064                    0.532097            0.0145985       0.937956                   -85.3603  34.1014            0.387728
9        0.800562                    0.0930877          0.216545  1.19898            0.0833333        0.0994864  0.461404                    0.477451            0.0218978       0.959854                   -78.3455  19.8976            0.258941
10       0.898876                    0.0752547          0.222732  1.0922             0.0857143        0.0826819  0.420312                    0.434273            0.0218978       0.981752                   -77.7268  9.21989            0.13472
11       1                           0.0478908          0.180454  1                  0.0694444        0.0672961  0.384831                    0.397163            0.0182482       1                          -81.9546  0                  0

ModelMetricsBinomial: stackedensemble
** Reported on cross-validation data. **

MSE: 0.13332964452798532
RMSE: 0.36514332053042586
LogLoss: 0.4251172777705303
Mean Per-Class Error: 0.18575642435756423
AUC: 0.8722711062227111
AUCPR: 0.8253325994790762
Gini: 0.7445422124454222

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.328281563653651
       no    yes    Error    Rate
-----  ----  -----  -------  -------------
no     360   78     0.1781   (78.0/438.0)
yes    53    221    0.1934   (53.0/274.0)
Total  413   299    0.184    (131.0/712.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.328282     0.771379  205
max f2                       0.175139     0.828841  259
max f0point5                 0.671388     0.786252  119
max accuracy                 0.476252     0.824438  170
max precision                0.981645     1         0
max recall                   0.0437366    1         388
max specificity              0.981645     1         0
max absolute_mcc             0.476252     0.625661  170
max min_per_class_accuracy   0.313406     0.810502  210
max mean_per_class_accuracy  0.328282     0.814244  205
max tns                      0.981645     438       0
max fns                      0.981645     273       0
max fps                      0.0260453    438       399
max tps                      0.0437366    274       388
max tnr                      0.981645     1         0
max fnr                      0.981645     0.99635   0
max fpr                      0.0260453    1         399
max tpr                      0.0437366    1         388

Gains/Lift Table: Avg response rate: 38.48 %, avg score: 38.57 %
group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score      cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  --------  -----------------  ---------------  ---------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.011236                    0.978925           2.59854   2.59854            1                0.980325   1                           0.980325            0.0291971       0.0291971                  159.854   159.854            0.0291971
2        0.0210674                   0.956132           2.59854   2.59854            1                0.973652   1                           0.977211            0.0255474       0.0547445                  159.854   159.854            0.0547445
3        0.0308989                   0.932345           2.22732   2.48042            0.857143         0.939856   0.954545                    0.965325            0.0218978       0.0766423                  122.732   148.042            0.0743592
4        0.0491573                   0.930175           2.59854   2.5243             1                0.930641   0.971429                    0.952443            0.0474453       0.124088                   159.854   152.43             0.121804
5        0.0519663                   0.928799           2.59854   2.52831            1                0.928799   0.972973                    0.951165            0.00729927      0.131387                   159.854   152.831            0.129104
6        0.101124                    0.885272           2.15308   2.3459             0.828571         0.908551   0.902778                    0.930449            0.105839        0.237226                   115.308   134.59             0.221245
7        0.150281                    0.87117            2.45005   2.37997            0.942857         0.875915   0.915888                    0.912611            0.120438        0.357664                   145.005   137.997            0.337116
8        0.200843                    0.815722           2.16545   2.32597            0.833333         0.842749   0.895105                    0.895024            0.109489        0.467153                   116.545   132.597            0.432907
9        0.300562                    0.593351           1.72016   2.12497            0.661972         0.72668    0.817757                    0.839171            0.171533        0.638686                   72.016    112.497            0.549645
10       0.400281                    0.372435           1.39077   1.94207            0.535211         0.486415   0.747368                    0.751292            0.138686        0.777372                   39.0768   94.2067            0.612989
11       0.5                         0.204476           0.988177  1.75182            0.380282         0.278219   0.674157                    0.656943            0.0985401       0.875912                   -1.18228  75.1825            0.611072
12       0.599719                    0.149737           0.329392  1.51531            0.126761         0.174134   0.583138                    0.576663            0.0328467       0.908759                   -67.0608  51.5308            0.502366
13       0.699438                    0.12537            0.182996  1.32536            0.0704225        0.13616    0.51004                     0.51386             0.0182482       0.927007                   -81.7004  32.536             0.36993
14       0.799157                    0.103092           0.256194  1.19195            0.0985915        0.114099   0.458699                    0.463978            0.0255474       0.952555                   -74.3806  19.1949            0.249358
15       0.898876                    0.0782622          0.292793  1.0922             0.112676         0.0928891  0.420312                    0.42281             0.0291971       0.981752                   -70.7207  9.21989            0.13472
16       1                           0.0260453          0.180454  1                  0.0694444        0.0560457  0.384831                    0.385722            0.0182482       1                          -81.9546  0                  0

Cross-Validation Metrics Summary:
                         mean        sd           cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  ----------  -----------  ------------  ------------  ------------  ------------  ------------
accuracy                 0.8300391   0.032300547  0.8466667     0.82758623    0.82222223    0.7832168     0.8705036
aic                      nan         0.0          nan           nan           nan           nan           nan
auc                      0.8777024   0.03292845   0.90392345    0.88503087    0.8698804     0.8248153     0.9048621
err                      0.1699609   0.032300547  0.15333334    0.1724138     0.17777778    0.21678321    0.1294964
err_count                24.2        4.6583257    23.0          25.0          24.0          31.0          18.0
f0point5                 0.7711801   0.034894176  0.7933579     0.78296703    0.7692308     0.71202534    0.79831934
f1                       0.78784496  0.029634291  0.78899086    0.8201439     0.7777778     0.74380165    0.80851066
f2                       0.8059456   0.034584176  0.78467155    0.8610272     0.78651685    0.7785467     0.8189655
lift_top_group           2.077621    1.192709     0.0           2.265625      2.54717       2.5535715     3.0217392
loglikelihood            nan         0.0          nan           nan           nan           nan           nan
---                      ---         ---          ---           ---           ---           ---           ---
mcc                      0.6472702   0.05551042   0.6686573     0.6641881     0.6300143     0.5623726     0.7111188
mean_per_class_accuracy  0.8260594   0.026641222  0.83301437    0.8342014     0.8169581     0.7868432     0.85928005
mean_per_class_error     0.17394058  0.026641222  0.16698565    0.1657986     0.18304187    0.21315682    0.14071997
mse                      0.13338934  0.02119763   0.118996195   0.14200978    0.1424468     0.15847196    0.10502196
pr_auc                   0.8300734   0.043809067  0.78652436    0.88275594    0.8152825     0.7956853     0.8701191
precision                0.7607814   0.041571077  0.7962963     0.76          0.76363635    0.6923077     0.7916667
r2                       0.43496087  0.074470796  0.4875762     0.42404407    0.40264773    0.33485365    0.52568275
recall                   0.8189109   0.043317452  0.7818182     0.890625      0.7924528     0.8035714     0.82608694
rmse                     0.36427552  0.029425308  0.34495825    0.37684184    0.37742126    0.39808536    0.32407093
specificity              0.83320796  0.05752175   0.8842105     0.7777778     0.8414634     0.77011496    0.8924731
[22 rows x 8 columns]


[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [18]:
lb = automl.leaderboard
lb.head(rows = lb.nrows)

model_id                                                              auc    logloss     aucpr    mean_per_class_error      rmse       mse
---------------------------------------------------------------  --------  ---------  --------  ----------------------  --------  --------
StackedEnsemble_AllModels_5_AutoML_2_20251006_24550              0.872271   0.425117  0.825333                0.185756  0.365143  0.13333
StackedEnsemble_BestOfFamily_4_AutoML_2_20251006_24550           0.868701   0.416975  0.842461                0.174566  0.360385  0.129877
GBM_lr_annealing_selection_AutoML_2_20251006_24550_select_model  0.868655   0.420345  0.843528                0.177299  0.361122  0.130409
GBM_grid_1_AutoML_2_20251006_24550_model_15                      0.866359   0.433446  0.838029                0.18004   0.368538  0.13582
StackedEnsemble_BestOfFamily_2_AutoML_2_20251006_24550           0.865368   0.422406  0.838062                0.176174  0.36171   0.130834
StackedEnsemble_AllModels_2_AutoML_2_20251006_24550              0.865022   0.41813   0.843632                0.176157  0.359062  0.128926
GBM_grid_1_AutoML_2_20251006_24550_model_17                      0.864872   0.423089  0.841374                0.187365  0.363398  0.132058
GBM_grid_1_AutoML_2_20251006_24550_model_2                       0.864759   0.41873   0.841578                0.174116  0.360152  0.12971
StackedEnsemble_BestOfFamily_3_AutoML_2_20251006_24550           0.864422   0.422989  0.837932                0.177774  0.36157   0.130733
GBM_grid_1_AutoML_2_20251006_24550_model_5                       0.864393   0.426749  0.840586                0.180974  0.363315  0.131998
StackedEnsemble_AllModels_1_AutoML_2_20251006_24550              0.863768   0.423427  0.835833                0.174341  0.361452  0.130648
GBM_3_AutoML_2_20251006_24550                                    0.863047   0.425098  0.832042                0.17115   0.360344  0.129848
GBM_5_AutoML_2_20251006_24550                                    0.863001   0.417892  0.848678                0.176616  0.359036  0.128907
GBM_grid_1_AutoML_2_20251006_24550_model_8                       0.86246    0.434802  0.844286                0.198064  0.369707  0.136683
GBM_4_AutoML_2_20251006_24550                                    0.862155   0.429356  0.837131                0.183465  0.364139  0.132597
StackedEnsemble_AllModels_3_AutoML_2_20251006_24550              0.861343   0.444541  0.836707                0.188731  0.373455  0.139468
GBM_grid_1_AutoML_2_20251006_24550_model_3                       0.860389   0.429185  0.839389                0.176382  0.365817  0.133822
GBM_grid_1_AutoML_2_20251006_24550_model_10                      0.860376   0.441276  0.826785                0.190064  0.371101  0.137716
StackedEnsemble_AllModels_4_AutoML_2_20251006_24550              0.859781   0.445811  0.836197                0.189614  0.373871  0.13978
XGBoost_grid_1_AutoML_2_20251006_24550_model_13                  0.859727   0.449693  0.827584                0.186898  0.370553  0.13731
GBM_grid_1_AutoML_2_20251006_24550_model_7                       0.859468   0.435943  0.835896                0.183023  0.367826  0.135296
GBM_grid_1_AutoML_2_20251006_24550_model_9                       0.858927   0.431947  0.834269                0.188714  0.366988  0.13468
GBM_grid_1_AutoML_2_20251006_24550_model_12                      0.857639   0.431982  0.831929                0.181649  0.366042  0.133987
XGBoost_grid_1_AutoML_2_20251006_24550_model_2                   0.857248   0.435787  0.828087                0.180265  0.368474  0.135773
DeepLearning_grid_1_AutoML_2_20251006_24550_model_1              0.857081   0.453687  0.824196                0.193314  0.374444  0.140209
XGBoost_grid_1_AutoML_2_20251006_24550_model_12                  0.855864   0.445136  0.819167                0.196464  0.373261  0.139324
XGBoost_grid_1_AutoML_2_20251006_24550_model_3                   0.855527   0.448437  0.825525                0.187115  0.369265  0.136357
XGBoost_2_AutoML_2_20251006_24550                                0.855098   0.44378   0.8225                  0.188265  0.373213  0.139288
XGBoost_grid_1_AutoML_2_20251006_24550_model_8                   0.85499    0.529669  0.818561                0.199905  0.391501  0.153273
StackedEnsemble_BestOfFamily_5_AutoML_2_20251006_24550           0.854215   0.464451  0.821432                0.198055  0.379877  0.144306
GBM_grid_1_AutoML_2_20251006_24550_model_1                       0.853102   0.448934  0.817679                0.179599  0.374872  0.140529
DRF_1_AutoML_2_20251006_24550                                    0.852498   0.463932  0.819937                0.19763   0.375779  0.14121
DeepLearning_grid_1_AutoML_2_20251006_24550_model_3              0.851736   0.494156  0.822714                0.192839  0.376495  0.141749
XRT_1_AutoML_2_20251006_24550                                    0.851727   0.460371  0.820207                0.18574   0.381305  0.145394
XGBoost_grid_1_AutoML_2_20251006_24550_model_1                   0.851152   0.445113  0.824385                0.195539  0.373289  0.139345
GBM_grid_1_AutoML_2_20251006_24550_model_11                      0.851077   0.465488  0.810206                0.206296  0.385548  0.148647
GLM_1_AutoML_2_20251006_24550                                    0.850677   0.451714  0.812064                0.213795  0.379743  0.144205
GBM_grid_1_AutoML_2_20251006_24550_model_4                       0.850523   0.454121  0.818279                0.194881  0.378136  0.142987
StackedEnsemble_BestOfFamily_1_AutoML_2_20251006_24550           0.85039    0.452264  0.810107                0.212695  0.378778  0.143473
XGBoost_grid_1_AutoML_2_20251006_24550_model_10                  0.850169   0.497811  0.813628                0.208129  0.388171  0.150677
XGBoost_grid_1_AutoML_2_20251006_24550_model_11                  0.84994    0.448282  0.822507                0.210396  0.375913  0.14131
DeepLearning_1_AutoML_2_20251006_24550                           0.849898   0.460422  0.806615                0.210404  0.378383  0.143174
XGBoost_grid_1_AutoML_2_20251006_24550_model_7                   0.84919    0.442767  0.829921                0.18734   0.373047  0.139164
XGBoost_grid_1_AutoML_2_20251006_24550_model_4                   0.848848   0.449474  0.82078                 0.20128   0.376661  0.141874
XGBoost_3_AutoML_2_20251006_24550                                0.848686   0.454588  0.823557                0.193964  0.375665  0.141124
DeepLearning_grid_1_AutoML_2_20251006_24550_model_2              0.847965   0.560173  0.826551                0.194422  0.372755  0.138947
GBM_grid_1_AutoML_2_20251006_24550_model_13                      0.847486   0.467446  0.805569                0.210612  0.384175  0.147591
DeepLearning_grid_2_AutoML_2_20251006_24550_model_1              0.84579    0.491545  0.809324                0.202405  0.386684  0.149524
XGBoost_1_AutoML_2_20251006_24550                                0.845599   0.457062  0.807897                0.206738  0.379846  0.144283
XGBoost_grid_1_AutoML_2_20251006_24550_model_14                  0.845261   0.455986  0.814959                0.209937  0.380278  0.144611
XGBoost_grid_1_AutoML_2_20251006_24550_model_5                   0.845045   0.457029  0.814348                0.204696  0.379545  0.144054
XGBoost_grid_1_AutoML_2_20251006_24550_model_6                   0.844103   0.455735  0.819639                0.204005  0.37894   0.143596
DeepLearning_grid_2_AutoML_2_20251006_24550_model_2              0.843253   0.457822  0.817088                0.200372  0.379735  0.144199
GBM_grid_1_AutoML_2_20251006_24550_model_16                      0.842237   0.46852   0.810647                0.224103  0.387108  0.149853
DeepLearning_grid_3_AutoML_2_20251006_24550_model_1              0.841178   0.509731  0.814913                0.215412  0.390879  0.152787
XGBoost_grid_1_AutoML_2_20251006_24550_model_9                   0.840262   0.464587  0.813888                0.216103  0.38415   0.147571
GBM_1_AutoML_2_20251006_24550                                    0.84012    0.471551  0.810836                0.221595  0.388295  0.150773
GBM_grid_1_AutoML_2_20251006_24550_model_6                       0.839799   0.476006  0.810109                0.226161  0.390825  0.152744
DeepLearning_grid_3_AutoML_2_20251006_24550_model_2              0.836012   0.464608  0.803492                0.211296  0.386011  0.149004
DeepLearning_grid_1_AutoML_2_20251006_24550_model_4              0.834621   0.498429  0.798764                0.209262  0.389105  0.151403
GBM_grid_1_AutoML_2_20251006_24550_model_14                      0.832833   0.493968  0.794658                0.236676  0.399814  0.159851
[61 rows x 7 columns]

In [19]:
# Show best model
best_model = automl.leader
best_model

Model Details
=============
H2OStackedEnsembleEstimator : Stacked Ensemble
Model Key: StackedEnsemble_AllModels_5_AutoML_2_20251006_24550


Model Summary for Stacked Ensemble:
key                                        value
-----------------------------------------  ----------------
Stacking strategy                          cross_validation
Number of base models (used / total)       51/51
# GBM base models (used / total)           22/22
# XGBoost base models (used / total)       17/17
# DeepLearning base models (used / total)  9/9
# DRF base models (used / total)           2/2
# GLM base models (used / total)           1/1
Metalearner algorithm                      GBM
Metalearner fold assignment scheme         Random
Metalearner nfolds                         5
Metalearner fold_column
Custom metalearner hyperparameters         None

ModelMetricsBinomial: stackedensemble
** Reported on train data. **

MSE: 0.09090845232882111
RMSE: 0.3015102856103272
LogLoss: 0.31432360504066814
Mean Per-Class Error: 0.11203879612038796
AUC: 0.9210995567109956
AUCPR: 0.9210650079351107
Gini: 0.8421991134219913

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.37033104806734146
       no    yes    Error    Rate
-----  ----  -----  -------  ------------
no     399   39     0.089    (39.0/438.0)
yes    37    237    0.135    (37.0/274.0)
Total  436   276    0.1067   (76.0/712.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.370331     0.861818  156
max f2                       0.240679     0.866619  184
max f0point5                 0.841168     0.886139  77
max accuracy                 0.438375     0.894663  147
max precision                0.944013     1         0
max recall                   0.0560809    1         396
max specificity              0.944013     1         0
max absolute_mcc             0.438375     0.776622  147
max min_per_class_accuracy   0.294054     0.875912  171
max mean_per_class_accuracy  0.370331     0.887961  156
max tns                      0.944013     438       0
max fns                      0.944013     273       0
max fps                      0.0478908    438       399
max tps                      0.0560809    274       396
max tnr                      0.944013     1         0
max fnr                      0.944013     0.99635   0
max fpr                      0.0478908    1         399
max tpr                      0.0560809    1         396

Gains/Lift Table: Avg response rate: 38.48 %, avg score: 39.72 %
group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score      cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  --------  -----------------  ---------------  ---------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.11236                     0.939851           2.59854   2.59854            1                0.940016   1                           0.940016            0.291971        0.291971                   159.854   159.854            0.291971
2        0.150281                    0.923634           2.59854   2.59854            1                0.933065   1                           0.938262            0.0985401       0.390511                   159.854   159.854            0.390511
3        0.200843                    0.89888            2.59854   2.59854            1                0.909343   1                           0.930982            0.131387        0.521898                   159.854   159.854            0.521898
4        0.300562                    0.743951           1.93976   2.37997            0.746479         0.830272   0.915888                    0.897568            0.193431        0.715328                   93.9755   137.997            0.674233
5        0.400281                    0.32432            1.57376   2.17913            0.605634         0.538723   0.838596                    0.808172            0.156934        0.872263                   57.3764   117.913            0.76724
6        0.501404                    0.17306            0.324818  1.80515            0.125            0.221091   0.694678                    0.689769            0.0328467       0.905109                   -67.5182  80.5148            0.656251
7        0.599719                    0.131035           0.18561   1.53965            0.0714286        0.146261   0.592506                    0.600669            0.0182482       0.923358                   -81.439   53.965             0.526097
8        0.699438                    0.109153           0.146397  1.34101            0.056338         0.119696   0.516064                    0.532097            0.0145985       0.937956                   -85.3603  34.1014            0.387728
9        0.800562                    0.0930877          0.216545  1.19898            0.0833333        0.0994864  0.461404                    0.477451            0.0218978       0.959854                   -78.3455  19.8976            0.258941
10       0.898876                    0.0752547          0.222732  1.0922             0.0857143        0.0826819  0.420312                    0.434273            0.0218978       0.981752                   -77.7268  9.21989            0.13472
11       1                           0.0478908          0.180454  1                  0.0694444        0.0672961  0.384831                    0.397163            0.0182482       1                          -81.9546  0                  0

ModelMetricsBinomial: stackedensemble
** Reported on cross-validation data. **

MSE: 0.13332964452798532
RMSE: 0.36514332053042586
LogLoss: 0.4251172777705303
Mean Per-Class Error: 0.18575642435756423
AUC: 0.8722711062227111
AUCPR: 0.8253325994790762
Gini: 0.7445422124454222

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.328281563653651
       no    yes    Error    Rate
-----  ----  -----  -------  -------------
no     360   78     0.1781   (78.0/438.0)
yes    53    221    0.1934   (53.0/274.0)
Total  413   299    0.184    (131.0/712.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.328282     0.771379  205
max f2                       0.175139     0.828841  259
max f0point5                 0.671388     0.786252  119
max accuracy                 0.476252     0.824438  170
max precision                0.981645     1         0
max recall                   0.0437366    1         388
max specificity              0.981645     1         0
max absolute_mcc             0.476252     0.625661  170
max min_per_class_accuracy   0.313406     0.810502  210
max mean_per_class_accuracy  0.328282     0.814244  205
max tns                      0.981645     438       0
max fns                      0.981645     273       0
max fps                      0.0260453    438       399
max tps                      0.0437366    274       388
max tnr                      0.981645     1         0
max fnr                      0.981645     0.99635   0
max fpr                      0.0260453    1         399
max tpr                      0.0437366    1         388

Gains/Lift Table: Avg response rate: 38.48 %, avg score: 38.57 %
group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score      cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  --------  -----------------  ---------------  ---------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.011236                    0.978925           2.59854   2.59854            1                0.980325   1                           0.980325            0.0291971       0.0291971                  159.854   159.854            0.0291971
2        0.0210674                   0.956132           2.59854   2.59854            1                0.973652   1                           0.977211            0.0255474       0.0547445                  159.854   159.854            0.0547445
3        0.0308989                   0.932345           2.22732   2.48042            0.857143         0.939856   0.954545                    0.965325            0.0218978       0.0766423                  122.732   148.042            0.0743592
4        0.0491573                   0.930175           2.59854   2.5243             1                0.930641   0.971429                    0.952443            0.0474453       0.124088                   159.854   152.43             0.121804
5        0.0519663                   0.928799           2.59854   2.52831            1                0.928799   0.972973                    0.951165            0.00729927      0.131387                   159.854   152.831            0.129104
6        0.101124                    0.885272           2.15308   2.3459             0.828571         0.908551   0.902778                    0.930449            0.105839        0.237226                   115.308   134.59             0.221245
7        0.150281                    0.87117            2.45005   2.37997            0.942857         0.875915   0.915888                    0.912611            0.120438        0.357664                   145.005   137.997            0.337116
8        0.200843                    0.815722           2.16545   2.32597            0.833333         0.842749   0.895105                    0.895024            0.109489        0.467153                   116.545   132.597            0.432907
9        0.300562                    0.593351           1.72016   2.12497            0.661972         0.72668    0.817757                    0.839171            0.171533        0.638686                   72.016    112.497            0.549645
10       0.400281                    0.372435           1.39077   1.94207            0.535211         0.486415   0.747368                    0.751292            0.138686        0.777372                   39.0768   94.2067            0.612989
11       0.5                         0.204476           0.988177  1.75182            0.380282         0.278219   0.674157                    0.656943            0.0985401       0.875912                   -1.18228  75.1825            0.611072
12       0.599719                    0.149737           0.329392  1.51531            0.126761         0.174134   0.583138                    0.576663            0.0328467       0.908759                   -67.0608  51.5308            0.502366
13       0.699438                    0.12537            0.182996  1.32536            0.0704225        0.13616    0.51004                     0.51386             0.0182482       0.927007                   -81.7004  32.536             0.36993
14       0.799157                    0.103092           0.256194  1.19195            0.0985915        0.114099   0.458699                    0.463978            0.0255474       0.952555                   -74.3806  19.1949            0.249358
15       0.898876                    0.0782622          0.292793  1.0922             0.112676         0.0928891  0.420312                    0.42281             0.0291971       0.981752                   -70.7207  9.21989            0.13472
16       1                           0.0260453          0.180454  1                  0.0694444        0.0560457  0.384831                    0.385722            0.0182482       1                          -81.9546  0                  0

Cross-Validation Metrics Summary:
                         mean        sd           cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  ----------  -----------  ------------  ------------  ------------  ------------  ------------
accuracy                 0.8300391   0.032300547  0.8466667     0.82758623    0.82222223    0.7832168     0.8705036
aic                      nan         0.0          nan           nan           nan           nan           nan
auc                      0.8777024   0.03292845   0.90392345    0.88503087    0.8698804     0.8248153     0.9048621
err                      0.1699609   0.032300547  0.15333334    0.1724138     0.17777778    0.21678321    0.1294964
err_count                24.2        4.6583257    23.0          25.0          24.0          31.0          18.0
f0point5                 0.7711801   0.034894176  0.7933579     0.78296703    0.7692308     0.71202534    0.79831934
f1                       0.78784496  0.029634291  0.78899086    0.8201439     0.7777778     0.74380165    0.80851066
f2                       0.8059456   0.034584176  0.78467155    0.8610272     0.78651685    0.7785467     0.8189655
lift_top_group           2.077621    1.192709     0.0           2.265625      2.54717       2.5535715     3.0217392
loglikelihood            nan         0.0          nan           nan           nan           nan           nan
---                      ---         ---          ---           ---           ---           ---           ---
mcc                      0.6472702   0.05551042   0.6686573     0.6641881     0.6300143     0.5623726     0.7111188
mean_per_class_accuracy  0.8260594   0.026641222  0.83301437    0.8342014     0.8169581     0.7868432     0.85928005
mean_per_class_error     0.17394058  0.026641222  0.16698565    0.1657986     0.18304187    0.21315682    0.14071997
mse                      0.13338934  0.02119763   0.118996195   0.14200978    0.1424468     0.15847196    0.10502196
pr_auc                   0.8300734   0.043809067  0.78652436    0.88275594    0.8152825     0.7956853     0.8701191
precision                0.7607814   0.041571077  0.7962963     0.76          0.76363635    0.6923077     0.7916667
r2                       0.43496087  0.074470796  0.4875762     0.42404407    0.40264773    0.33485365    0.52568275
recall                   0.8189109   0.043317452  0.7818182     0.890625      0.7924528     0.8035714     0.82608694
rmse                     0.36427552  0.029425308  0.34495825    0.37684184    0.37742126    0.39808536    0.32407093
specificity              0.83320796  0.05752175   0.8842105     0.7777778     0.8414634     0.77011496    0.8924731
[22 rows x 8 columns]


[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [20]:
# Evaluate performance on both traind and test set
performance_train = best_model.model_performance(test_data = train_data)
performance_test = best_model.model_performance(test_data = test_data)

In [21]:
# Report statistics
print("Train Accuracy score: ", performance_train.accuracy())
print("Train AUC score: ", performance_train.auc())

print("Test Accuracy score: ", performance_test.accuracy())
print("Test AUC score: ", performance_test.auc())

Train Accuracy score:  [[0.4383746211142458, 0.8946629213483146]]
Train AUC score:  0.9210995567109956
Test Accuracy score:  [[0.30239445910527846, 0.8435754189944135]]
Test AUC score:  0.8739401165871753

In [22]:
# Save the best model
model_path = '/content/drive/MyDrive/Colab Notebooks/Kaggle/h2omodel_Titanic01'
h2o.save_model(model=best_model, path = model_path, force = True)

'/content/drive/MyDrive/Colab Notebooks/Kaggle/h2omodel_Titanic01/StackedEnsemble_AllModels_5_AutoML_2_20251006_24550'

In [ ]:
print(automl.feature_importance(data))

Computing feature importance via permutation shuffling for 8 features using 891 rows with 5 shuffle sets...
	3.39s	= Expected runtime (0.68s per shuffle set)
	0.85s	= Actual runtime (Completed 5 of 5 shuffle sets)

              importance    stddev   p_value  n  p99_high   p99_low
Sex             0.204040  0.020130  0.000011  5  0.245489  0.162592
Pclass          0.102581  0.008346  0.000005  5  0.119766  0.085397
Age             0.101908  0.007751  0.000004  5  0.117868  0.085948
Fare            0.078563  0.009323  0.000023  5  0.097759  0.059368
SibSp           0.020875  0.003773  0.000123  5  0.028644  0.013107
CabinNoCabin    0.010101  0.003722  0.001863  5  0.017765  0.002437
Parch           0.005387  0.002905  0.007150  5  0.011369 -0.000594
Embarked        0.005387  0.001463  0.000594  5  0.008400  0.002374

# PREDICTION

In [23]:
# Reading new data
new_data = pd.read_csv("test.csv")
new_data["CabinNoCabin"] = np.where(new_data["Cabin"].isnull(), "No Cabin", "Cabin")
new_data.drop(["PassengerId", "Name", "Ticket", "Cabin"], axis = 1, inplace = True)

new_data = h2o.H2OFrame(new_data)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [25]:
# Read saved model
loaded_model = h2o.load_model('/content/drive/MyDrive/Colab Notebooks/Kaggle/h2omodel_Titanic01/StackedEnsemble_AllModels_5_AutoML_2_20251006_24550')
loaded_model

Model Details
=============
H2OStackedEnsembleEstimator : Stacked Ensemble
Model Key: StackedEnsemble_AllModels_5_AutoML_2_20251006_24550


Model Summary for Stacked Ensemble:
key                                        value
-----------------------------------------  ----------------
Stacking strategy                          cross_validation
Number of base models (used / total)       51/51
# GBM base models (used / total)           22/22
# XGBoost base models (used / total)       17/17
# DeepLearning base models (used / total)  9/9
# DRF base models (used / total)           2/2
# GLM base models (used / total)           1/1
Metalearner algorithm                      GBM
Metalearner fold assignment scheme         Random
Metalearner nfolds                         5
Metalearner fold_column
Custom metalearner hyperparameters         None

ModelMetricsBinomial: stackedensemble
** Reported on train data. **

MSE: 0.09090845232882111
RMSE: 0.3015102856103272
LogLoss: 0.31432360504066814
Mean Per-Class Error: 0.11203879612038796
AUC: 0.9210995567109956
AUCPR: 0.9210650079351107
Gini: 0.8421991134219913

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.37033104806734146
       no    yes    Error    Rate
-----  ----  -----  -------  ------------
no     399   39     0.089    (39.0/438.0)
yes    37    237    0.135    (37.0/274.0)
Total  436   276    0.1067   (76.0/712.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.370331     0.861818  156
max f2                       0.240679     0.866619  184
max f0point5                 0.841168     0.886139  77
max accuracy                 0.438375     0.894663  147
max precision                0.944013     1         0
max recall                   0.0560809    1         396
max specificity              0.944013     1         0
max absolute_mcc             0.438375     0.776622  147
max min_per_class_accuracy   0.294054     0.875912  171
max mean_per_class_accuracy  0.370331     0.887961  156
max tns                      0.944013     438       0
max fns                      0.944013     273       0
max fps                      0.0478908    438       399
max tps                      0.0560809    274       396
max tnr                      0.944013     1         0
max fnr                      0.944013     0.99635   0
max fpr                      0.0478908    1         399
max tpr                      0.0560809    1         396

Gains/Lift Table: Avg response rate: 38.48 %, avg score: 39.72 %
group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score      cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  --------  -----------------  ---------------  ---------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.11236                     0.939851           2.59854   2.59854            1                0.940016   1                           0.940016            0.291971        0.291971                   159.854   159.854            0.291971
2        0.150281                    0.923634           2.59854   2.59854            1                0.933065   1                           0.938262            0.0985401       0.390511                   159.854   159.854            0.390511
3        0.200843                    0.89888            2.59854   2.59854            1                0.909343   1                           0.930982            0.131387        0.521898                   159.854   159.854            0.521898
4        0.300562                    0.743951           1.93976   2.37997            0.746479         0.830272   0.915888                    0.897568            0.193431        0.715328                   93.9755   137.997            0.674233
5        0.400281                    0.32432            1.57376   2.17913            0.605634         0.538723   0.838596                    0.808172            0.156934        0.872263                   57.3764   117.913            0.76724
6        0.501404                    0.17306            0.324818  1.80515            0.125            0.221091   0.694678                    0.689769            0.0328467       0.905109                   -67.5182  80.5148            0.656251
7        0.599719                    0.131035           0.18561   1.53965            0.0714286        0.146261   0.592506                    0.600669            0.0182482       0.923358                   -81.439   53.965             0.526097
8        0.699438                    0.109153           0.146397  1.34101            0.056338         0.119696   0.516064                    0.532097            0.0145985       0.937956                   -85.3603  34.1014            0.387728
9        0.800562                    0.0930877          0.216545  1.19898            0.0833333        0.0994864  0.461404                    0.477451            0.0218978       0.959854                   -78.3455  19.8976            0.258941
10       0.898876                    0.0752547          0.222732  1.0922             0.0857143        0.0826819  0.420312                    0.434273            0.0218978       0.981752                   -77.7268  9.21989            0.13472
11       1                           0.0478908          0.180454  1                  0.0694444        0.0672961  0.384831                    0.397163            0.0182482       1                          -81.9546  0                  0

ModelMetricsBinomial: stackedensemble
** Reported on cross-validation data. **

MSE: 0.13332964452798532
RMSE: 0.36514332053042586
LogLoss: 0.4251172777705303
Mean Per-Class Error: 0.18575642435756423
AUC: 0.8722711062227111
AUCPR: 0.8253325994790762
Gini: 0.7445422124454222

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.328281563653651
       no    yes    Error    Rate
-----  ----  -----  -------  -------------
no     360   78     0.1781   (78.0/438.0)
yes    53    221    0.1934   (53.0/274.0)
Total  413   299    0.184    (131.0/712.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.328282     0.771379  205
max f2                       0.175139     0.828841  259
max f0point5                 0.671388     0.786252  119
max accuracy                 0.476252     0.824438  170
max precision                0.981645     1         0
max recall                   0.0437366    1         388
max specificity              0.981645     1         0
max absolute_mcc             0.476252     0.625661  170
max min_per_class_accuracy   0.313406     0.810502  210
max mean_per_class_accuracy  0.328282     0.814244  205
max tns                      0.981645     438       0
max fns                      0.981645     273       0
max fps                      0.0260453    438       399
max tps                      0.0437366    274       388
max tnr                      0.981645     1         0
max fnr                      0.981645     0.99635   0
max fpr                      0.0260453    1         399
max tpr                      0.0437366    1         388

Gains/Lift Table: Avg response rate: 38.48 %, avg score: 38.57 %
group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score      cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  --------  -----------------  ---------------  ---------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.011236                    0.978925           2.59854   2.59854            1                0.980325   1                           0.980325            0.0291971       0.0291971                  159.854   159.854            0.0291971
2        0.0210674                   0.956132           2.59854   2.59854            1                0.973652   1                           0.977211            0.0255474       0.0547445                  159.854   159.854            0.0547445
3        0.0308989                   0.932345           2.22732   2.48042            0.857143         0.939856   0.954545                    0.965325            0.0218978       0.0766423                  122.732   148.042            0.0743592
4        0.0491573                   0.930175           2.59854   2.5243             1                0.930641   0.971429                    0.952443            0.0474453       0.124088                   159.854   152.43             0.121804
5        0.0519663                   0.928799           2.59854   2.52831            1                0.928799   0.972973                    0.951165            0.00729927      0.131387                   159.854   152.831            0.129104
6        0.101124                    0.885272           2.15308   2.3459             0.828571         0.908551   0.902778                    0.930449            0.105839        0.237226                   115.308   134.59             0.221245
7        0.150281                    0.87117            2.45005   2.37997            0.942857         0.875915   0.915888                    0.912611            0.120438        0.357664                   145.005   137.997            0.337116
8        0.200843                    0.815722           2.16545   2.32597            0.833333         0.842749   0.895105                    0.895024            0.109489        0.467153                   116.545   132.597            0.432907
9        0.300562                    0.593351           1.72016   2.12497            0.661972         0.72668    0.817757                    0.839171            0.171533        0.638686                   72.016    112.497            0.549645
10       0.400281                    0.372435           1.39077   1.94207            0.535211         0.486415   0.747368                    0.751292            0.138686        0.777372                   39.0768   94.2067            0.612989
11       0.5                         0.204476           0.988177  1.75182            0.380282         0.278219   0.674157                    0.656943            0.0985401       0.875912                   -1.18228  75.1825            0.611072
12       0.599719                    0.149737           0.329392  1.51531            0.126761         0.174134   0.583138                    0.576663            0.0328467       0.908759                   -67.0608  51.5308            0.502366
13       0.699438                    0.12537            0.182996  1.32536            0.0704225        0.13616    0.51004                     0.51386             0.0182482       0.927007                   -81.7004  32.536             0.36993
14       0.799157                    0.103092           0.256194  1.19195            0.0985915        0.114099   0.458699                    0.463978            0.0255474       0.952555                   -74.3806  19.1949            0.249358
15       0.898876                    0.0782622          0.292793  1.0922             0.112676         0.0928891  0.420312                    0.42281             0.0291971       0.981752                   -70.7207  9.21989            0.13472
16       1                           0.0260453          0.180454  1                  0.0694444        0.0560457  0.384831                    0.385722            0.0182482       1                          -81.9546  0                  0

Cross-Validation Metrics Summary:
                         mean        sd           cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  ----------  -----------  ------------  ------------  ------------  ------------  ------------
accuracy                 0.8300391   0.032300547  0.8466667     0.82758623    0.82222223    0.7832168     0.8705036
aic                      nan         0.0          nan           nan           nan           nan           nan
auc                      0.8777024   0.03292845   0.90392345    0.88503087    0.8698804     0.8248153     0.9048621
err                      0.1699609   0.032300547  0.15333334    0.1724138     0.17777778    0.21678321    0.1294964
err_count                24.2        4.6583257    23.0          25.0          24.0          31.0          18.0
f0point5                 0.7711801   0.034894176  0.7933579     0.78296703    0.7692308     0.71202534    0.79831934
f1                       0.78784496  0.029634291  0.78899086    0.8201439     0.7777778     0.74380165    0.80851066
f2                       0.8059456   0.034584176  0.78467155    0.8610272     0.78651685    0.7785467     0.8189655
lift_top_group           2.077621    1.192709     0.0           2.265625      2.54717       2.5535715     3.0217392
loglikelihood            nan         0.0          nan           nan           nan           nan           nan
---                      ---         ---          ---           ---           ---           ---           ---
mcc                      0.6472702   0.05551042   0.6686573     0.6641881     0.6300143     0.5623726     0.7111188
mean_per_class_accuracy  0.8260594   0.026641222  0.83301437    0.8342014     0.8169581     0.7868432     0.85928005
mean_per_class_error     0.17394058  0.026641222  0.16698565    0.1657986     0.18304187    0.21315682    0.14071997
mse                      0.13338934  0.02119763   0.118996195   0.14200978    0.1424468     0.15847196    0.10502196
pr_auc                   0.8300734   0.043809067  0.78652436    0.88275594    0.8152825     0.7956853     0.8701191
precision                0.7607814   0.041571077  0.7962963     0.76          0.76363635    0.6923077     0.7916667
r2                       0.43496087  0.074470796  0.4875762     0.42404407    0.40264773    0.33485365    0.52568275
recall                   0.8189109   0.043317452  0.7818182     0.890625      0.7924528     0.8035714     0.82608694
rmse                     0.36427552  0.029425308  0.34495825    0.37684184    0.37742126    0.39808536    0.32407093
specificity              0.83320796  0.05752175   0.8842105     0.7777778     0.8414634     0.77011496    0.8924731
[22 rows x 8 columns]


[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [26]:
# Predict new dataset
prediction = loaded_model.predict(new_data)
prediction

stackedensemble prediction progress: |███████████████████████████████████████████| (done) 100%

predict          no        yes
---------  --------  ---------
no         0.807319  0.192681
no         0.671003  0.328997
no         0.725192  0.274808
no         0.884     0.116
yes        0.245502  0.754498
no         0.886555  0.113445
yes        0.423773  0.576227
no         0.868888  0.131112
yes        0.288778  0.711222
no         0.927545  0.0724547
[418 rows x 3 columns]

In [27]:
h2o.export_file(prediction, "survived01_h2omodel.csv")

Export File progress: |██████████████████████████████████████████████████████████| (done) 100%

# FINDING THE CUT-OFF POINT

In [54]:
"""
y_def = test_data.as_data_frame(use_pandas=True)["survived"]
y_true = np.where(y_def == "yes", 1, 0)
y_true = pd.DataFrame(y_true)
y_true["survived"] = y_true[0]
y_true.drop([0], axis = 1, inplace = True)
y_true
"""

'\ny_def = test_data.as_data_frame(use_pandas=True)["survived"]\ny_true = np.where(y_def == "yes", 1, 0)\ny_true = pd.DataFrame(y_true)\ny_true["survived"] = y_true[0]\ny_true.drop([0], axis = 1, inplace = True)\ny_true\n'

In [55]:
# df = pd.read_csv("test.csv")
# df

In [56]:
h2o.shutdown()

H2O session _sid_9a7f closed.

/tmp/ipython-input-2900054706.py:1: H2ODeprecationWarning: Deprecated, use ``h2o.cluster().shutdown()``.
  h2o.shutdown()